### ISSUE TITLE
Breaks in 2D for certain input

### ISSUE THREAD

**Issue by mourner** [mikolalysenko/incremental-delaunay#2]
```js
var points = [];
for (var i = 0; i < 200000; i++) {
    points.push([
        Math.random() * 1e5,
        Math.random() * 1e5
    ]);
}

delaunay(2, points);
```

Breaks with the following error:

```js
        c.next.prev = c.prev
                    ^

TypeError: Cannot set property 'prev' of null
    at DelaunayTriangulation.dproto.insert (/Users/mourner/projects/delaunator/node_modules/incremental-delaunay/delaunay.js:157:21)
    at createDelaunayTriangulation (/Users/mourner/projects/delaunator/node_modules/incremental-delaunay/delaunay.js:242:21)
```

The problem happens less frequently if you multiply the coords by a higher value (e.g. 1e10). Perhaps some issues in the robust math? Or maybe it breaks on near-duplicate points? cc @mikolalysenko

**Comment by mikolalysenko** [comment]
This module is broken, need to add a deprecation warning.  Use the one based on convex hull or cdt2d instead

**Comment by mourner** [comment]
@mikolalysenko thanks! Any clue what part of the module is broken? When it works, it seems much faster than the other two.
